[book]
authors = ["5alv1.py", "Osconadi", "Yurimiva"]
language = "en"
multilingual = false
src = "src"
title = "7H3 N074710N 15 54V3D"

#[build]
#create-missing = false

#use as mdbook preprocessor
#[preprocessor.auto-gen-summary]
#first-line-as-link-text = true # indicate mdbook to make the first line(default the file name) of markdown file as the link text in 

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

